server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index detail.php index.php index.html;

    # Sistem Routing Dinamis: Sadaya URL dialungkeun ka detail.php
    location / {
        try_files $uri $uri/ /detail.php?$query_string;
    }

    # Nyambungkeun Nginx ka PHP-FPM
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index detail.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}